name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    environment: testSonar  # ✅ This line enables access to environment secrets like SONAR_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with Supabase
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          DB_USER: ${{ secrets.SUPABASE_DB_USER }}
          DB_PASS: ${{ secrets.SUPABASE_DB_PASS }}
        run: |
          echo "🔗 Connecting to Supabase at $DB_URL..."
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Bisan-Meera_Cooking \
            -Dsonar.organization=bisan-meera \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
